export const VALIDATE = 'Validate'
export const ONLY_DEV = 'Only Developer Role'
export const CDP = 'CDP'
export const IMAGE = 'IMAGE'
export const CRON = 'Cron Jobs'
export const WORKFLOW = ' Workflow'

export * as CommonSchemas from './common.js'
export * as CdpSchemas from './cdp.js'
export * as ImageSchemas from './image.js'
export * as AuthSchemas from './auth.js'
