/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from 'ethers'
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from '@nomicfoundation/hardhat-ethers/types'

import * as Contracts from '.'

declare module 'hardhat/types/runtime' {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: 'Lock',
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Lock__factory>
    getContractFactory(
      name: 'MockERC20',
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.MockERC20__factory>
    getContractFactory(
      name: 'IERC20',
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IERC20__factory>
    getContractFactory(
      name: 'IERC721',
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IERC721__factory>
    getContractFactory(
      name: 'IERC721Receiver',
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.IERC721Receiver__factory>
    getContractFactory(
      name: 'TreasuryForwarder',
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.TreasuryForwarder__factory>

    getContractAt(
      name: 'Lock',
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.Lock>
    getContractAt(
      name: 'MockERC20',
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.MockERC20>
    getContractAt(
      name: 'IERC20',
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.IERC20>
    getContractAt(
      name: 'IERC721',
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.IERC721>
    getContractAt(
      name: 'IERC721Receiver',
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.IERC721Receiver>
    getContractAt(
      name: 'TreasuryForwarder',
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<Contracts.TreasuryForwarder>

    deployContract(
      name: 'Lock',
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.Lock>
    deployContract(
      name: 'MockERC20',
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.MockERC20>
    deployContract(
      name: 'IERC20',
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IERC20>
    deployContract(
      name: 'IERC721',
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IERC721>
    deployContract(
      name: 'IERC721Receiver',
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IERC721Receiver>
    deployContract(
      name: 'TreasuryForwarder',
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.TreasuryForwarder>

    deployContract(
      name: 'Lock',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.Lock>
    deployContract(
      name: 'MockERC20',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.MockERC20>
    deployContract(
      name: 'IERC20',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IERC20>
    deployContract(
      name: 'IERC721',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IERC721>
    deployContract(
      name: 'IERC721Receiver',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.IERC721Receiver>
    deployContract(
      name: 'TreasuryForwarder',
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<Contracts.TreasuryForwarder>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<ethers.ContractFactory>
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer,
    ): Promise<ethers.ContractFactory>
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer,
    ): Promise<ethers.Contract>
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<ethers.Contract>
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions,
    ): Promise<ethers.Contract>
  }
}
