/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockTokenSol from './MockToken.sol'
export type { mockTokenSol }
import type * as simpleForwarderSol from './SimpleForwarder.sol'
export type { simpleForwarderSol }
export type { Lock } from './Lock'
export * as factories from './factories'
export { Lock__factory } from './factories/Lock__factory'
export type { MockERC20 } from './MockToken.sol/MockERC20'
export { MockERC20__factory } from './factories/MockToken.sol/MockERC20__factory'
export type { IERC20 } from './SimpleForwarder.sol/IERC20'
export { IERC20__factory } from './factories/SimpleForwarder.sol/IERC20__factory'
export type { IERC721 } from './SimpleForwarder.sol/IERC721'
export { IERC721__factory } from './factories/SimpleForwarder.sol/IERC721__factory'
export type { IERC721Receiver } from './SimpleForwarder.sol/IERC721Receiver'
export { IERC721Receiver__factory } from './factories/SimpleForwarder.sol/IERC721Receiver__factory'
export type { TreasuryForwarder } from './SimpleForwarder.sol/TreasuryForwarder'
export { TreasuryForwarder__factory } from './factories/SimpleForwarder.sol/TreasuryForwarder__factory'
