/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers'
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from '../common'

export interface TreasuryForwarderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'TREASURY'
      | 'forwardERC20'
      | 'forwardERC721'
      | 'forwardETH'
      | 'onERC721Received',
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'TREASURY', values?: undefined): string
  encodeFunctionData(functionFragment: 'forwardERC20', values: [AddressLike]): string
  encodeFunctionData(functionFragment: 'forwardERC721', values: [AddressLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'forwardETH', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'onERC721Received',
    values: [AddressLike, AddressLike, BigNumberish, BytesLike],
  ): string

  decodeFunctionResult(functionFragment: 'TREASURY', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'forwardERC20', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'forwardERC721', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'forwardETH', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result
}

export interface TreasuryForwarder extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryForwarder
  waitForDeployment(): Promise<this>

  interface: TreasuryForwarderInterface

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>

  TREASURY: TypedContractMethod<[], [string], 'view'>

  forwardERC20: TypedContractMethod<[token: AddressLike], [void], 'nonpayable'>

  forwardERC721: TypedContractMethod<
    [token: AddressLike, tokenId: BigNumberish],
    [void],
    'nonpayable'
  >

  forwardETH: TypedContractMethod<[], [void], 'nonpayable'>

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, tokenId: BigNumberish, arg3: BytesLike],
    [string],
    'nonpayable'
  >

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T

  getFunction(nameOrSignature: 'TREASURY'): TypedContractMethod<[], [string], 'view'>
  getFunction(
    nameOrSignature: 'forwardERC20',
  ): TypedContractMethod<[token: AddressLike], [void], 'nonpayable'>
  getFunction(
    nameOrSignature: 'forwardERC721',
  ): TypedContractMethod<[token: AddressLike, tokenId: BigNumberish], [void], 'nonpayable'>
  getFunction(nameOrSignature: 'forwardETH'): TypedContractMethod<[], [void], 'nonpayable'>
  getFunction(
    nameOrSignature: 'onERC721Received',
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, tokenId: BigNumberish, arg3: BytesLike],
    [string],
    'nonpayable'
  >

  filters: {}
}
